### ISSUE TITLE
can you post a photo of how you modified your stock motor controller?

### ISSUE THREAD

**Issue by aluminumwelder** [ldocull/MaslowDue#1]
can you post a photo of how you modified your stock motor controller? I want to try this modification but I am a novice at electronics. Is it better to solder the additional components to the top of the motor shield or to the bottom of the arudino due?

**Comment by ldocull** [comment]
I used a Mega shield proto board, put all the parts and tricky wiring there instead of modifying the motor-shield or the Due.

RobotDyn - Mega Protoshield Prototype Shield with Mini breadboard, for Arduino Mega 2560 (Assembled) https://www.amazon.com/dp/B071JDRGGR/ref=cm_sw_r_cp_api_i_5eNJCbGQCR9E7

**Comment by ldocull** [comment]
Electronics info posted
