### ISSUE TITLE
Timer3

### ISSUE THREAD

**Issue by madgrizzle** [ldocull/MaslowDue#11]
I was hoping you could help clarify something for me.  I'm trying to understand the code and timer usage (again).

In stepper.cpp, Timer3 appears to be used in place of delay_ms in the st_go_idle() function.

```// Set stepper driver idle state, disabled or enabled, depending on settings and circumstances.
  if (((settings.stepper_idle_lock_time != 0xff) || sys_rt_exec_alarm || sys.state == STATE_SLEEP) && sys.state != STATE_HOMING) {
    // Force stepper dwell to lock axes for a defined amount of time to ensure the axes come to a complete
    // stop and not drift from residual inertial forces at the end of the last movement.
    #ifndef MASLOWCNC
      delay_ms(settings.stepper_idle_lock_time);
    #else
      Timer3.attachInterrupt(stepperTimeoutHandler).start(settings.stepper_idle_lock_time * 1000);
    #endif
    pin_state = true; // Override. Disable steppers.
  }
  if (bit_istrue(settings.flags,BITFLAG_INVERT_ST_ENABLE)) { pin_state = !pin_state; } // Apply pin invert.
```
looking at the code, it seems that right after starting off Timer 3, the pin_state=True and the following conditional line gets executed.  Then, after the timer goes off, the exact same lines are called in stepperTimeoutHandler, but in reverse order:

```
void stepperTimeoutHandler(void)
{
  Timer3.stop();
  if (bit_istrue(settings.flags,BITFLAG_INVERT_ST_ENABLE)) { pin_state = !pin_state; } // Apply pin invert.
    pin_state = true; // Override. Disable steppers.
}
```

I'm not sure the purpose of the function and it appears to me that all the timeout handler does is sets pin_state to true when it was already set to true earlier right after starting the timer (I'm assuming the BITFLAG_INVERT_ST_ENABLE is false).  In the non-Maslow grbl, it seems to wait before setting it to true.

**Comment by ldocull** [comment]
Since the Maslow does not use steppers, this timeout is not really used. The function comes from GRBL, but is not really used other than to manage consistent timing.
