### ISSUE TITLE
What is the best way to cool the L298 chips? Is the ThroughHole version of the chip better for cooling. 

### ISSUE THREAD

**Issue by metalmaslow** [ldocull/MaslowDue#12]
What is the best way to cool the L298 chips? Is the ThroughHole version of the chip better for cooling? I want to get some of these DUE shields made up in China, but I am worried about the L298 chips overheating like I have seen on the first generation Maslow Boards. Is the board with laser support available as open source?

**Comment by ldocull** [comment]
The Due design uses the ICs in a better way than before, so less heat is generated. You should still use some sort of heat sink. The thru hole device is not necessarily better - just different.
