### ISSUE TITLE
A question..

### ISSUE THREAD

**Issue by TheOncomingStorm** [ldocull/MaslowDue#18]
Does this firmware work with GroundControl/WebControl or is it Makerverse only?

**Comment by Maxattax97** [comment]
This firmware is based on Grbl, a widely used industry standard (unlike GroundControl)... as such, there is a plethora of software available, you can find some listed here: https://github.com/gnea/grbl/wiki/Using-Grbl

@ldocull and I used [bCNC](https://github.com/vlachoudis/bCNC) extensively while developing this.

**Comment by ldocull** [comment]
Thanks! I forget to look.

**Comment by TheOncomingStorm** [comment]
I hate to reopen this but I forgot to ask and this is relevant. For calibration I need to be able to nudge each individual motor until the sprockets' teeth line up to the "12 o'clock" so I can get accurate measurements. How can I do this? Ground/Webcontrol had that functionality but Makerverse didn't at all that I have managed to find and it drives me nuts. It took me 2 days(and I mean full 8+ hour days) to get Makerverse's calibration system to get me within a couple mm of accuracy, and I need sub-1mm accuracy or else I might as well sell this thing. bCNC doesn't seem to deal with this at all so I have to ask.

**Comment by ldocull** [comment]
Thanks for the contact. I will echo this message to MakerMade who would
offer the support on this issue.
Best,
Larry

**Comment by pelsound** [comment]
@TheOncomingStorm Please send your question via email to: support@makermade.com and we can help.
Thanks,
Joel
