### ISSUE TITLE
25LC256 (SPI) vs 24LC256 (I2C)

### ISSUE THREAD

**Issue by hfb3** [ldocull/MaslowDue#4]
While I was looking at your page, I noticed that your images and gerber files reference the 
use of a 25LC256 (SPI) eeprom, but your BOM references using a 24LC256 (I2C) eeprom.

**Comment by ldocull** [comment]
24LC256 is the proper part

**Comment by ldocull** [comment]
I have adjusted the picture accordingly. Thanks for the tip!
