### ISSUE TITLE
Is this board compatable with TLE2506 Maslow boards or just original boards?

### ISSUE THREAD

**Issue by aluminumwelder** [ldocull/MaslowDue#5]
is the due and prototype board compatible with this TLE controller?
http://maslowcommunitygarden.org/TLE5206-PowerControl-Boards.html

If not can you possibly make one that is? I can send you a TLE2506 control board for testing if you want.

**Comment by ldocull** [comment]
I believe that it can be made to work. A couple of cuts on the board to keep 5V off the I/O of the Due and the remapping of the PWM signals in software. I will have to look closer at how PWMs are assigned to the selected pins to make sure we can drive the motors in the same way (tertiary mode, which the 5206 looks to support).  I accept the offer of a board or two for testing, and will look into it further once I get a board from you. Connect to me by email at ldocull@gmail.com and I will send you shipping info.  Thanks!
