### ISSUE TITLE
Consider using IOREF instead of 5v or 3v3 

### ISSUE THREAD

**Issue by blurfl** [ldocull/MaslowDue#6]
The Arduino Mega2560 and Due boards provide IOREF which is directly connected to the power supply appropriate for the board. It is found among the the pins of the POWER header. If the power bus of the shield were connected to IOREF instead of 5v or 3v3, the shield should be safe to use with either a Mega or Due.

**Comment by ldocull** [comment]
Good idea, I’ll look into this for the future. Thanks!
