### ISSUE TITLE
adding AUX control to the board.

### ISSUE THREAD

**Issue by aluminumwelder** [ldocull/MaslowDue#7]
Is there any chance AUX controls can be added to this board? Or maybe they are already there and I just need to be shown where? I noticed a pattern of holes on the board are those for adding aux pins? Edited to add:  maybe silk screening of AUX 1 to 4 and aux 5 and 6 can be added to the silk screen layer. would this be good for adding the aux pins?  https://www.digikey.com/product-detail/en/TSW-104-07-T-T/SAM10848-ND/2685894/?itemSeq=291944890
would solder paste be a lot easier? I think I will try by hand first. thanks for any feedback

**Comment by ldocull** [comment]
All good thoughts!
