### ISSUE TITLE
Would it be possible to get ODB++ files out of Altium uploaded here?

### ISSUE THREAD

**Issue by cmullins70** [ldocull/MaslowDue#8]
This would eliminate the need for any manual data entry when uploading to Macrofab.com

**Comment by ldocull** [comment]
I’ll see if I can’t get some posted shortly. Thanks

**Comment by ldocull** [comment]
Added the ODB files per your request.

**Comment by cmullins70** [comment]
Worked beautifully - thank you!

<img width="1672" alt="Screen Shot 2019-06-13 at 8 36 53 AM" src="https://user-images.githubusercontent.com/6732434/59437132-9aab6980-8db6-11e9-9f7d-0acaeb5b54ed.png">
